# Do not waste vertical space.
add_newline = false

# Be more lenient with timeouts.
command_timeout = 1000

[aws]
disabled = true

[battery]
disabled = true

[directory]
repo_root_style = "bold blue"
truncation_symbol = "…/"

[docker_context]
disabled = true

[gcloud]
disabled = true

[nodejs]
disabled = true

[rlang]
disabled = true
