#!/bin/sh

printf '%s ' '+INBOX'
dir="$1"
if [ -d "$dir" ]; then
  cd "$dir"
  find -E . -type d ! -regex '.*(cur|new|tmp)' ! -path '*INBOX*' ! -path . \
    | sed "s;\./\(.*\);+'\1';" \
    | sort \
    | tr '\n' ' '
fi
