#!/bin/sh
#
# This shell script generates a temporary irssi config out of an encrypted part
# containing user credentials and non-sensitive base stub.

cfg='/tmp/irssi-config'

set -e
touch $cfg
chmod 600 $cfg
gpg --no-tty -d ~/.irssi/config.sensitive.asc > $cfg
cat ~/.irssi/config >> $cfg
(sleep 2 && rm $cfg) &
exec irssi --config=$cfg
