#!/usr/bin/env sh

limelight -m config width 1
limelight -m config radius 8
limelight -m config placement exterior
limelight -m config active_color 0xFF40FF00
limelight -m config normal_color 0x00FFFFFF

echo "limelight configuration loaded.."