#!/usr/bin/env bash

set -euo pipefail

tool_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
target="$tool_dir/config.toml"

{
  printf '# Generated by codex/build-config.sh; edit config.base.toml and projects.toml.\n'
  printf '\n'
  sed '$a\' "$tool_dir/config.base.toml"
  if [[ -f "$tool_dir/projects.toml" ]]; then
    printf '\n'
    sed '$a\' "$tool_dir/projects.toml"
  fi
} > "$target"
